[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
# Name on PyPI must be available.
# pip install dev-library
name = "dev-library"
version = "0.1.0"
description = "Development project description"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"

authors = [
  { name = "Anna Burova", email = "burova.anna+git@gmail.com" }
]

dependencies = [
]

keywords = [
  "keyword1",
  "keyword2",
  "keyword3",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Utilities",
  "Operating System :: OS Independent",
]

[project.optional-dependencies]
test = [
]

[project.urls]
homepage = "https://github.com/AnnaBurova/dev-library"
repository = "https://github.com/AnnaBurova/dev-library"
issues = "https://github.com/AnnaBurova/dev-library/issues"
changelog = "https://github.com/AnnaBurova/dev-library/blob/main/CHANGELOG.md"

[tool.hatch.build.targets.wheel]
packages = ["library"]
only-packages = true

[tool.hatch.build.targets.sdist]
only-include = [
  "src/library",
  "pyproject.toml",
  "LICENSE",
  "README.md",
]
exclude = [
  "__pycache__",
  ".env",
  ".git",
  ".github",
  "*.log",
  "*.pyc",
  "tests",
]
